---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/oauth: oauth2_proxy
  name: app
spec:
  rules:
  - host: app.192.168.100.99.nip.io
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              number: 8080
  tls:
  - hosts:
    - app.192.168.100.99.nip.io
